### ISSUE TITLE
Fixes - Reporte de SonarCloud status failed

### ISSUE THREAD

**Issue by knlopenknowledge** [EL-BID/Fontagro#1]
El último commit al repo originó que el reporte en Sonarcloud saliera failed, recomendamos revisen el reporte ya que indica que la causa de estofue principalmente por lineas duplicadas de código. 

Ver detalles aquí:
https://sonarcloud.io/component_measures?id=EL-BID_Fontagro&metric=new_duplicated_lines_density&selected=EL-BID_Fontagro%3Aapplication%2Fmodels%2FComponente.php&view=list

**Comment by szsebas** [comment]
Hicimos refactor de código y ya marca "passed"

**Comment by knlopenknowledge** [comment]
Genial @sebasanimus gracias, proceso a cerrar este issue
